services:
  gibbon:
    image: niosem/gibbon-docker:latest
    container_name: gibbon
    restart: unless-stopped
    ports:
      - "2010:2010"
    volumes:
      - gibbon_data:/var/www/html
    
  db:
    image: mariadb:latest
    container_name: gibbon-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gibbon
      MYSQL_USER: gibbon
      MYSQL_PASSWORD: gibbon
    volumes:
      - gibbon_db:/var/lib/mysql

volumes:
  gibbon_data:
    driver: local
  gibbon_db:
    driver: local